spring:
  application:
    name: dalston-config-server-git
  cloud:
    config:
      server:
        git:
           uri: https://github.com/chiminwon/config-repo-demo.git
#          uri: http://git.oschina.net/didispace/config-repo-demo/
           search-paths: repo
           username: chiminwon@gmail.com
           password: 1qaz!QAZ

server:
  port: 1201

eureka:  
  client:  
    service-url:  
      defaultZone: http://localhost:1001/eureka/
